### ISSUE TITLE
Failed to install 'cordova-background-geolocation' for ios

### ISSUE THREAD

**Issue by m8xp0w3r** [transistorsoft/cordova-plugin-background-fetch#168]
## Your Environment
* Plugin version: 7.2.0
* Platform: iOS
* OS version: -
* Device manufacturer / model: -
* Cordova version (`cordova -v`): 12.0.0 (cordova-lib@12.0.1)
* Cordova platform version (`cordova platform ls`): android 12.0.0, ios 7.0.0
* Plugin config -

## Expected Behavior
`cordova platform add ios` should add the ios platform and install the plugin

## Actual Behavior
Installing the plugin fails with an error `Failed to install 'cordova-background-geolocation'`. Error details below.

## Steps to Reproduce
1. cordova plugin add ios

## Context
We are currently updating cordova to version 12. After removing the current platforms (iOS and Android) and updating all dependencies, adding the iOS platform fails with the error mentioned below.

## Debug logs

```
Using cordova-fetch for cordova-ios
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: de.diloc.DiLocSyncMobile
        Name: DiLoc|Sync
iOS project created with cordova-ios@7.0.0
Installing "cc.fovea.cordova.openwith" for ios
Installing "cc.fovea.cordova.openwith" dependencies
Copying "cc.fovea.cordova.openwith/ShareExtension" to ios...
Installing "cordova-android-support-gradle-release" for ios
Installing "cordova-background-geolocation" for ios
Plugin dependency "cordova-plugin-background-fetch@7.1.2" already fetched, using that version.
Installing "cordova-plugin-background-fetch" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-background-geolocation': Error [ERR_UNHANDLED_ERROR]: Uh oh!
Unhandled error. ('"framework" tag with type "podspec" is no longer supported. Please use the "podspec" tag.')
    at new NodeError (node:internal/errors:400:5)
    at CordovaEventEmitter.emit (node:events:502:17)
    at CordovaEventEmitter.emit (/Users/nleistner/.nvm/versions/node/v18.13.0/lib/node_modules/cordova/node_modules/cordova-common/src/events.js:69:22)
    at install (/Users/nleistner/Developer/work/DiLocSyncClient/native/cordova/node_modules/cordova-ios/lib/plugman/pluginHandlers.js:100:32)
    at ActionStack.process (/Users/nleistner/Developer/work/DiLocSyncClient/native/cordova/node_modules/cordova-common/src/ActionStack.js:55:25)
    at PluginManager.doOperation (/Users/nleistner/Developer/work/DiLocSyncClient/native/cordova/node_modules/cordova-common/src/PluginManager.js:111:24)
    at PluginManager.addPlugin (/Users/nleistner/Developer/work/DiLocSyncClient/native/cordova/node_modules/cordova-common/src/PluginManager.js:141:21)
    at Api.addPlugin (/Users/nleistner/Developer/work/DiLocSyncClient/native/cordova/node_modules/cordova-ios/lib/Api.js:258:14)
    at handleInstall (/Users/nleistner/.nvm/versions/node/v18.13.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /Users/nleistner/.nvm/versions/node/v18.13.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
Uh oh!
Unhandled error. ('"framework" tag with type "podspec" is no longer supported. Please use the "podspec" tag.')
```

**Comment by m8xp0w3r** [comment]
Sorry. Wrong repository... 🙈
