### ISSUE TITLE
Cannot install plugin, destination for source file is located outside the project

### ISSUE THREAD

**Issue by skylarmt** [transistorsoft/cordova-plugin-background-fetch#99]
## Your Environment
* Plugin version: 5.4.1
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/A
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.1.0
* Plugin config: N/A

## Expected Behavior
The plugin should install when I run `cordova plugin add cordova-plugin-background-fetch`.

## Actual Behavior
    Installing "cordova-plugin-background-fetch" for android
    ANDROID_HOME=/home/skylar/Android/Sdk
    JAVA_HOME=/usr/lib/jvm/java-8-oracle
    Subproject Path: CordovaLib
    Subproject Path: app
    
    > Configure project :CordovaLib
    publishNonDefault is deprecated and has no effect anymore. All variants are now published.
    
    > Configure project :app
    Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
    The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
            at build_b9vl78qa2xcq3flo0cnqlwszh.run(/home/skylar/censored-cordova-project-folder/platforms/android/app/build.gradle:144)
    
    
    BUILD SUCCESSFUL in 0s
    3 actionable tasks: 1 executed, 2 up-to-date
    Error during processing of action! Attempting to revert...
    Failed to install 'cordova-plugin-background-fetch': CordovaError: Uh oh!
    Destination "/home/skylar/censored-cordova-project-folder/libs/com/transistorsoft/tsbackgroundfetch" for source file "/home/skylar/censored-cordova-project-folder/plugins/cordova-plugin-background-fetch/src/android/libs/com/transistorsoft/tsbackgroundfetch" is located outside the project
        at copyFile (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/lib/pluginHandlers.js:245:50)
        at install (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/lib/pluginHandlers.js:86:13)
        at Object.process (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
        at PluginManager.doOperation (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
        at PluginManager.addPlugin (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
        at /home/skylar/censored-cordova-project-folder/platforms/android/cordova/Api.js:247:74
        at _fulfilled (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/q/q.js:854:54)
        at self.promiseDispatch.done (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/q/q.js:883:30)
        at Promise.promise.promiseDispatch (/home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/q/q.js:816:13)
        at /home/skylar/censored-cordova-project-folder/platforms/android/cordova/node_modules/q/q.js:624:44
    (node:3144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Uh oh!
    Destination "/home/skylar/censored-cordova-project-folder/libs/com/transistorsoft/tsbackgroundfetch" for source file "/home/skylar/censored-cordova-project-folder/plugins/cordova-plugin-background-fetch/src/android/libs/com/transistorsoft/tsbackgroundfetch" is located outside the project

## Context
Install the plugin.

## Debug logs
N/A

**Comment by christocracy** [comment]
When in doubt, 

```
$ cordova platform remove android
$ cordova platform add android
```
Try again

**Comment by skylarmt** [comment]
🤦 That worked, thanks...

**Comment by christocracy** [comment]
Remember this in the future.
